title: Heavily Embedded Denny's Seat Crumb II 
description: >-
  Tangents and code.
baseurl: 
url: "http://www.mobile-bungalow.github.io" 
github_username: mobile-bungalow 

theme: minima
plugins:
  - jekyll-feed
